runtime: python39
entrypoint: gunicorn -b :$PORT serverOllama:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  OLLAMA_API_URL: 'http://localhost:11434/api/generate'
  MODEL_NAME: 'gemma3:4b'